# Generated by Django 3.2.9 on 2021-12-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(default='Papacito', max_length=128),
            preserve_default=False,
        ),
    ]
